spring.jpa:
  database: POSTGRESQL
  hibernate.ddl-auto: update
  show-sql: true
  hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

spring.datasource:
  driverClassName: org.postgresql.Driver
  url: jdbc:postgresql://127.0.0.1:5432/invoicedetails
  username: postgres
  password: "7$Rt6&m,6&Ui4!as9^Yu2"
  
server:
  port : 8090